#!/usr/bin/perl
## nappit add-on lyrionmusicserver
## last updated Aug. 2025, script by urknall
############
## setup lyrionmusicserver
##
####################################################################################
#
#
####################################################################################

####################
# not on Solaris  11, included
####################
     $ant=`uname -a`;
     @par=split(/ /,$ant);
     if ($par[3]=~/^11\./i) {
       print "\n"x20;
       print "This installer is running on Illumos based systems only.\nOn Solaris 11\n\n";
       exit;
     }

###############
### root only !
###############
     $ant=`whoami`; chomp $ant;
     if ($ant ne "root") {
         print "user $ant not allowed\nlogin as root or su and run setup again!";
         exit;
     }

#run from $HOME ie /root
###############
               $t=`pwd`;
               $ant=`echo \$HOME`;
               if ($t ne $ant){
                      print "\n\n#####################\nYou must call wget as from your \$HOME-directory.\n Please do a cd /\$HOME and try again.\n\n";
                      exit;
               }

##date
#######
 ($sec,$min,$hour,$mday,$mon,$year,$wday,$ydat,$isdst) = localtime(time);
 $mon++;
 if ($min < 10)  { $min  = "0$min";  }
 if ($hour < 10) { $hour = "0$hour"; }
 if ($mday < 10) { $mday = "0$mday"; }
 if ($mon < 10)  { $mon  = "0$mon";  }
 $year=1900+$year;



##############
# Startmessage
##############
$t=`echo \$HOME`;
chomp($t);        # remove newline

      print "\n"x20;
      print "***************************************************************************\n\n";
      print "**    Setup napp-it addon lyrionmusicserver                              **\n";
      print "**    intended for OmniOS not on Solaris 11                              **\n";     
      print "**    currently only omnios r151046 with perl 5.36 is supported          **\n\n";
      print "***************************************************************************\n\n\n";
      print "*  \n";
      sleep(3);
      print " 3 \n"; sleep(2);
      print " 2 \n"; sleep(2);
      print " 1 \n"; sleep(2);

print "\n"x40;


#########################################################
## step 1. create BE, optionally add path to all commands
#########################################################

    # create BE pre setup
    $t=time();
    `beadm create pre_lyrionmusicserver`;
    
    print "installing needed packages\n";
    `pkg install --deny-new-be git`;


#############################
## step 2: Install lms
#############################

    print "installing lyrionmusicserver\n";
    `git clone https://github.com/urknall/lyrionmusicserver-omnios.git lyrionmusicserver-omnios.git`;
    
    `useradd -c 'lmsd' -d /var/empty -s /bin/false lmsd`;
    `groupadd lmsd`;
    
    `mkdir /opt/lyrionmusicserver`;
    `cp -r /root/lyrionmusicserver-omnios.git/lyrionmusicserver/* /opt/lyrionmusicserver`;
    `chown -R lmsd:lmsd /opt/lyrionmusicserver`;
    `chmod -R 755 /opt/lyrionmusicserver`;
    
    `mkdir /var/lib/squeezeboxserver`;
    `chown lmsd:lmsd /var/lib/squeezeboxserver`;
    `chmod 755 /var/lib/squeezeboxserver`;

    `cp /root/lyrionmusicserver-omnios.git/svc-lmsd /lib/svc/method`;
    `chmod 555  /lib/svc/method/svc-lmsd`;
    `chown root:bin  /lib/svc/method/svc-lmsd`;
    
    `cp /root/lyrionmusicserver-omnios.git/lmsd.xml /lib/svc/manifest/network`;
    `chmod 444 /lib/svc/manifest/network/lmsd.xml`;
    `chown root:sys /lib/svc/manifest/network/lmsd.xml`;
    
    `svccfg import /lib/svc/manifest/network/lmsd.xml`;
    `svcadm enable lmsd`;
